solr:
  image: solr
  ports:
   - "8983:8983"
  volumes:
    - collection1:/opt/solr/server/solr/collection1
  entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - collection1